project_x/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashboard.views import error_404, error_500
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404
handler500 = error_500

admin.site.site_header = 'Панель администрирования'
admin.site.site_title = 'Школа искусств'

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),

    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView
         .as_view(template_name="users/password_reset_confirm.html",
                  success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView
         .as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),

    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models


class User(AbstractUser):
    class Gender(models.TextChoices):
        M = 'M'
        F = 'F'

    class Types(models.TextChoices):
        ADMIN = 'ADMIN', 'admin'
        STAFF = 'STAFF', 'staff'
        PARENT = 'PARENT', 'parent'
        STUDENT = 'STUDENT', 'student'

    address = models.CharField(blank=True, null=True, max_length=100, verbose_name='Адрес')
    passport = models.CharField(blank=True, null=True, max_length=100, verbose_name='Данные паспорта')
    type = models.CharField(max_length=7, choices=Types.choices, default=Types.STUDENT, verbose_name='Тип записи')
    gender = models.CharField(blank=True, null=True, max_length=1, choices=Gender.choices)
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone_number = models.CharField(validators=[phoneNumberRegex], blank=True, null=True, max_length=16, unique=True,
                                    verbose_name='Номер телефона')
    photo = models.ImageField(upload_to="users/images/%Y/%m/%d", blank=True, null=True, verbose_name="Фотография")
    date_of_birth = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    memo = models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Family(models.Model):
    parent = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='students')
    student = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, null=True, blank=True,
                                related_name='parents')

    def __str__(self):
        return f'{self.parent}: {self.student}'

users/forms.py
from datetime import date

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django import forms


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput())
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput())
    email = forms.CharField(label='E-mail', widget=forms.EmailInput())
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        required = ['username', 'email', 'password1', 'password2']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким e-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    photo = forms.ImageField(required=False, label='Фото')
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.CharField(disabled=True, label='E-mail')
    date_of_birth = forms.DateField(required=False, label='Дата рождения')
    first_name = forms.CharField(required=False, label="Имя")
    last_name = forms.CharField(required=False, label="Фамилия")

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name',
                  'date_of_birth', 'address', 'memo']
        widgets = {
            'photo': forms.ImageField(),
            'username': forms.TextInput(),
            'email': forms.EmailInput(),
            'date_of_birth': forms.DateInput(),
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'memo': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
        }

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        if date_of_birth is not None:
            oldest = date.today().year - 100
            youngest = date.today().year - 5
            if not oldest <= date_of_birth.year <= youngest:
                raise forms.ValidationError(f'Выберите дату между годами {oldest} и {youngest}!')
        return date_of_birth


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput())
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput())
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput())

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from dashboard.utils import ExtraContextMixin
from project_x import settings
from users.forms import RegisterUserForm, LoginUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(ExtraContextMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    template_title = 'Авторизация'
    btn_submit_title = 'Авторизоваться'


class RegisterUser(ExtraContextMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    template_title = 'Регистрация'
    btn_submit_title = 'Отправить'


class ProfileUser(LoginRequiredMixin, ExtraContextMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')
    template_title = 'Профиль пользователя'
    btn_submit_title = 'Обновить'

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, default_user_image=settings.DEFAULT_USER_IMAGE)

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

users/templates/users/auth_block.html
{% if user.is_authenticated %}
    <form id="logout-form" method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <a class="btn btn-outline-success" href="{% url 'users:profile' %}">
            {% if user.first_name %}{{ user.first_name }} {{ user.last_name }}
                {% else %}{{ user.username }}{% endif %}
        </a>
        <button class="btn btn-outline-secondary" type="submit">Выйти</button>
    </form>
{% else %}
    <a class="btn btn-outline-success" href="{% url 'users:login' %}">Войти</a>
    <a class="btn btn-outline-secondary" href="{% url 'users:register' %}">Зарегистрироваться</a>
{% endif %}

users/templates/users/el_change_password.html
<a class="ml-auto" href="{% url 'users:password_change' %}">Сменить пароль</a>

users/templates/users/form_handler.html
<!-- Template title -->
<div class="m-1 text-center"><h1>{{ template_title }}</h1></div>
<!-- Form type and container width -->
{% if template_title == 'Профиль пользователя' %}
    <div class="container-fluid custom-width-350 form-group">
    <form method="post" enctype="multipart/form-data">

    {% if user.photo %}
        {% include 'users/user_photo_handler.html' %}
    {% else %}
        <p class="text-center"><img class="rounded img-thumbnail w-75 shadow-lg" src="{{ default_user_image }}">
    {% endif %}

{% else %}
    <div class="container-fluid text-center custom-width-300 form-group">
    <form method="post">
{% endif %}

{% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

<!-- Form body -->
{% for f in form %}
    <div class="form-floating mt-3">
        <input class="form-control shadow-lg"
                {% if f.field.disabled %}
               disabled
                {% endif %}
               name="{{ f.name }}"
               type="{{ f.field.widget.input_type }}"
               id="{{ f.id_for_label }}" autocomplete="off"
                {% if f.name == 'date_of_birth' %}
               value="{% if f.value %}{{ f.value|date:"d.m.Y" }}{% endif %}"
                {% else %}
               value="{% if f.value %}{{ f.value }}{% endif %}"
                {% endif %}
               placeholder="">
        <label for="{{ f.id_for_label }}">{{ f.label }}</label>
        <div class="form-error">{{ f.errors }}</div>
    </div>
{% endfor %}

<!-- Buttons and extra elements -->
{% if template_title == 'Регистрация' %}
    <div class="text-center px-0 pt-3">
        <button class="btn btn-info" type="submit">{{ btn_submit_title }}</button>
    </div>
{% else %}
    <div class="container px-0 pt-3 d-flex justify-content-between align-items-center">
    <button class="float-start btn btn-info" type="submit">{{ btn_submit_title }}</button>
{% endif %}
{% if template_title == 'Авторизация' %}{% include 'users/el_forgot_password.html' %}{% endif %}
{% if template_title == 'Профиль пользователя' %}{% include 'users/el_change_password.html' %}{% endif %}
</div>

</form>
</div>

users/templates/users/login.html
{% extends 'master.html' %}

{% block content %}


    <h1>{{ title }}</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="">{{ f.error }}</div>
        {% endfor %}

        <p><button type="submit">Войти</button></p>

{#        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>#}
    </form>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'master.html' %}

{% block content %}
    <div class="m-1 text-center"><h1>Пароль успешно изменен!</h1></div>

    <div class="container-fluid custom-width-350 form-group">
    <div class="text-center"><a href="{% url 'users:profile' %}">Вернуться в профиль</a></div>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'master.html' %}

{% block content %}
    <div class="m-1 text-center"><h1>Сброс пароля</h1></div>

    <div class="container-fluid custom-width-350 form-group">
        <form method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <div class="form-floating mt-3">
                    <input class="form-control shadow-lg"
                           name="{{ f.name }}"
                           type="{{ f.field.widget.input_type }}"
                           id="{{ f.id_for_label }}" autocomplete="on"
                           value="{% if f.value %}{{ f.value }}{% endif %}"
                           placeholder="">
                    <label for="{{ f.id_for_label }}">{{ f.label }}</label>

                    <div class="">{{ f.error }}</div>
                </div>
            {% endfor %}
            <div class="text-center mt-3">
                <button class="btn btn-info" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "master.html" %}

{% block content %}
    <div class="m-1 text-center"><h1>Сброс пароля</h1></div>

    <div class="container-fluid text-center custom-width-500 form-group">
        <p>На указанный адрес электронной почты отправлены инструкции по восстановлению пароля.</p>
        <p>В случае, если письмо получено не было, убедитесь, что вы указали тот же адрес, что и при регистрации,
        а также проверьте в папках нежелательной почты.</p>
    </div>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% translate "You're receiving this email because you requested a password reset for your user account at " %}{{ site_name }}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'master.html' %}

{% block content %}
    <div class="m-1 text-center"><h1>Восстановление пароля</h1></div>

    <div class="container-fluid custom-width-350 form-group">
        <form method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <div class="form-floating mt-3">
                    <input class="form-control shadow-lg"
                           name="{{ f.name }}"
                           type="{{ f.field.widget.input_type }}"
                           id="{{ f.id_for_label }}" autocomplete="on"
                           value="{% if f.value %}{{ f.value }}{% endif %}"
                           placeholder="">
                    <label for="{{ f.id_for_label }}">{{ f.label }}</label>

                    <div class="">{{ f.error }}</div>
                </div>
            {% endfor %}
            <div class="text-center mt-3">
                <button class="btn btn-info" type="submit">Отправить ссылку о сбросе на e-mail</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/photo_handler.html
{% load user_tags %}

{% external_image_hosting as hosting %}
{% with hosting|length|stringformat:"i" as hl %}
    {% with sliced_tale=hl|concat_strings:":" sliced_head=":"|concat_strings:hl %}
        {% with user.photo.url|slice:sliced_tale|slice:sliced_head as part_of_user_photo_url %}
            {% if part_of_user_photo_url == hosting %}
                {% with user.photo.url|slice:sliced_tale as path %}
                    <p class="text-center"><img class="rounded img-thumbnail w-75 shadow-lg"
                                                src="{{ 'https://'|concat_strings:path }}">
                {% endwith %}
            {% else %}
                <p class="text-center"><img class="rounded img-thumbnail w-75 shadow-lg" src="{{ user.photo.url }}">
            {% endif %}
        {% endwith %}
    {% endwith %}
{% endwith %}

users/templates/users/profile.html
{% extends 'master.html' %}

{% block content %}
    {% include 'users/form_handler.html' %}
{% endblock %}

users/templates/users/register.html
{% extends 'master.html' %}

{% block content %}
    {% include 'users/form_handler.html' %}
{% endblock %}

users/templates/users/register_done.html
{% extends 'master.html' %}

{% block content %}
    <h1>Добро пожаловать!</h1>

    <p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a
            href="{% url 'users:login' %}">ссылке</a>
    </p>
{% endblock %}

users/templates/users/user_photo_handler.html
{% load user_tags %}

{% external_image_hosting as hosting %}
{% with hosting|length|stringformat:"i" as hl %}
    {% with sliced_tale=hl|concat_strings:":" sliced_head=":"|concat_strings:hl %}
        {% with user.photo.url|slice:sliced_tale|slice:sliced_head as part_of_user_photo_url %}
            {% if part_of_user_photo_url == hosting %}
                {% with user.photo.url|slice:sliced_tale as path %}
                    <p class="text-center"><img class="rounded img-thumbnail w-75 shadow-lg"
                                                src="{{ 'https://'|concat_strings:path }}">
                {% endwith %}
            {% else %}
                <p class="text-center"><img class="rounded img-thumbnail w-75 shadow-lg" src="{{ user.photo.url }}">
            {% endif %}
        {% endwith %}
    {% endwith %}
{% endwith %}